name: tmux
version: '3.2'
summary: Access and control terminals (or windows) from a single terminal.
description: |
        tmux is a "terminal multiplexer", it enables a number of terminals (or windows)
        to be accessed and controlled from a single terminal. tmux is intended to be a
        simple, modern, BSD-licensed alternative to programs such as GNU screen.
#icon: https://icon-icons.com/downloadimage.php?id=131831&root=2148/SVG/&file=tmux_icon_131831.svg
grade: stable # Use stable or devel
confinement: classic
license: ISC
base: core20

architectures:
  - build-on: [amd64]
    run-on: [armhf, arm64, amd64]

apps:
        tmux:
                command: usr/local/bin/tmux

parts:
        tmux:
                plugin: autotools
                source: https://github.com/tmux/tmux/releases/download/3.2/tmux-3.2.tar.gz
                build-packages:
                        - make
                        - libevent-dev
                        - libncurses-dev
                        - libtinfo5
                stage-packages:
                        - libevent-dev
#                organize: 
#                        tmux: bin/
